# Generated by Django 4.2.5 on 2023-09-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='solped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMERO', models.CharField(max_length=50)),
                ('FECHA', models.DateField(blank=True, null=True)),
                ('OFICINA', models.CharField(blank=True, max_length=255, null=True)),
                ('TOTAL', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('DETALLE', models.CharField(blank=True, max_length=255, null=True)),
                ('ESTADO', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Solicitud de pedido',
                'verbose_name_plural': 'Solicitudes de pedidos',
            },
        ),
    ]
