# Generated by Django 4.1.7 on 2023-09-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solped',
            old_name='OFICINA',
            new_name='ARTICULO',
        ),
        migrations.AddField(
            model_name='solped',
            name='CANTIDAD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='solped',
            name='CATEGORIA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solped',
            name='CONCEPTO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solped',
            name='FUENTE_FINANCIAMIENTO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solped',
            name='OBJETO_NUMERO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solped',
            name='PRECIO',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='solped',
            name='SECRETARIA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solped',
            name='SECRETARIA_NOMBRE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solped',
            name='SECRETARIA_NUMERO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
