# Generated by Django 4.2.5 on 2023-09-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_rename_oficina_solped_articulo_solped_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solped',
            name='DETALLE',
            field=models.TextField(blank=True, null=True),
        ),
    ]
